"""initial schema

Revision ID: 7e52f4a06009
Revises: 
Create Date: 2026-03-18 19:00:53.092405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e52f4a06009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('eia_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.Enum('US', 'CA', name='country'), nullable=False),
    sa.Column('state_province', sa.String(length=50), nullable=False),
    sa.Column('utility_type', sa.Enum('IOU', 'MUNICIPAL', 'COOPERATIVE', 'POLITICAL_SUBDIVISION', 'FEDERAL', 'STATE', 'RETAIL_MARKETER', 'BEHIND_METER', 'COMMUNITY_CHOICE', 'OTHER', name='utilitytype'), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('tariff_page_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilities_country'), 'utilities', ['country'], unique=False)
    op.create_index(op.f('ix_utilities_eia_id'), 'utilities', ['eia_id'], unique=True)
    op.create_index(op.f('ix_utilities_name'), 'utilities', ['name'], unique=False)
    op.create_index(op.f('ix_utilities_state_province'), 'utilities', ['state_province'], unique=False)
    op.create_table('monitoring_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('check_frequency_days', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('UNCHANGED', 'CHANGED', 'ERROR', 'PENDING', name='monitoringstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_sources_utility_id'), 'monitoring_sources', ['utility_id'], unique=False)
    op.create_table('service_territories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zip_codes', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('postal_code_prefixes', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_territories_utility_id'), 'service_territories', ['utility_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('customer_class', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'LIGHTING', name='customerclass'), nullable=False),
    sa.Column('rate_type', sa.Enum('FLAT', 'TOU', 'TIERED', 'DEMAND', 'SEASONAL', 'TOU_TIERED', 'SEASONAL_TOU', 'SEASONAL_TIERED', 'DEMAND_TOU', 'COMPLEX', name='ratetype'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_document_hash', sa.String(length=64), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('openei_id', sa.String(length=50), nullable=True),
    sa.Column('raw_openei_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('energy_schedule_weekday', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('energy_schedule_weekend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demand_schedule_weekday', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demand_schedule_weekend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_customer_class'), 'tariffs', ['customer_class'], unique=False)
    op.create_index(op.f('ix_tariffs_openei_id'), 'tariffs', ['openei_id'], unique=True)
    op.create_index(op.f('ix_tariffs_rate_type'), 'tariffs', ['rate_type'], unique=False)
    op.create_index(op.f('ix_tariffs_utility_id'), 'tariffs', ['utility_id'], unique=False)
    op.create_table('monitoring_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'REVIEWED', 'DISMISSED', name='reviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['monitoring_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_logs_source_id'), 'monitoring_logs', ['source_id'], unique=False)
    op.create_table('rate_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('ENERGY', 'DEMAND', 'FIXED', 'MINIMUM', 'ADJUSTMENT', name='componenttype'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('rate_value', sa.Float(), nullable=False),
    sa.Column('tier_min_kwh', sa.Float(), nullable=True),
    sa.Column('tier_max_kwh', sa.Float(), nullable=True),
    sa.Column('tier_label', sa.String(length=100), nullable=True),
    sa.Column('period_index', sa.Integer(), nullable=True),
    sa.Column('period_label', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('adjustment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_components_tariff_id'), 'rate_components', ['tariff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_components_tariff_id'), table_name='rate_components')
    op.drop_table('rate_components')
    op.drop_index(op.f('ix_monitoring_logs_source_id'), table_name='monitoring_logs')
    op.drop_table('monitoring_logs')
    op.drop_index(op.f('ix_tariffs_utility_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_rate_type'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_openei_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_customer_class'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_service_territories_utility_id'), table_name='service_territories')
    op.drop_table('service_territories')
    op.drop_index(op.f('ix_monitoring_sources_utility_id'), table_name='monitoring_sources')
    op.drop_table('monitoring_sources')
    op.drop_index(op.f('ix_utilities_state_province'), table_name='utilities')
    op.drop_index(op.f('ix_utilities_name'), table_name='utilities')
    op.drop_index(op.f('ix_utilities_eia_id'), table_name='utilities')
    op.drop_index(op.f('ix_utilities_country'), table_name='utilities')
    op.drop_table('utilities')
    # ### end Alembic commands ###
